### ISSUE TITLE
Add protocol spec/description

### ISSUE THREAD

**Issue by joschi** [urso/go-lumber-old#4]
There is a protocol description for the old Lumberjack protocol at https://github.com/logstash-plugins/logstash-input-beats/blob/v2.0.0/PROTOCOL.md but I'm missing like this for the Beats protocol.

While having a working library for the Lumberjack/Beats protocol is nice and a specification could be "reverse engineered" by looking at the Go code, it would be great if a textual protocol spec of the Lumberjack (v1) and Beats (v2) protocols existed.

**Comment by urso** [comment]
Project moved to elastic/go-lumber. New issue created in new repo.
